name: Github_Actions_Study 

on:
  push:
    branches: [ "main" ]

jobs:
  diretory-print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: create-vite-env  
        run: |
          chmod 777 -R front
          cat <<EOL > front/.env
          VITE_PORTONE_STOREID=${{ secrets.VITE_PORTONE_STOREID }}
          VITE_PORTONE_API_KEY=${{ secrets.VITE_PORTONE_API_KEY }}
          EOL
          cat front/.env

      - name: create-vite-env  
        run: |
          chmod 777 -R back
          cat <<EOL > back/src/main/resources/application-secret.yml
          spring:
            config:
              activate:
                on-profile: secret

            datasource:
              driver-class-name: com.mysql.cj.jdbc.Driver
              url: jdbc:mysql://${{ secrets.EC2_PUBLIC_IP}}:3306/${{ secrets.DATABASE_NAME }}
              username: ${{ secrets.DATABASE_USERNAME }}
              password: ${{ secrets.DATABASE_PASSWORD }}
        
            jwt:
              secret: ${{ secrets.JWT_SECRET }}
            EOL
            cat back/src/main/resources/application-secret.yml
